services:
  - type: web
    name: attendease-backend
    runtime: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: attendease-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STORAGE_TYPE
        value: cloudinary
      - key: UPLOAD_DIR
        value: /tmp/student_images
      - key: FACE_DETECTION_METHOD
        value: mediapipe
      - key: FACE_EMBEDDING_MODEL
        value: Facenet512
      - key: FACE_RECOGNITION_TOLERANCE
        value: 0.75
      - key: FACE_DETECTION_CONFIDENCE
        value: 0.6
      - key: LOG_LEVEL
        value: INFO
      - key: ALLOWED_ORIGINS
        value: "https://attendease-shikher-09.streamlit.app,http://localhost:8501"
    healthCheckPath: /health

databases:
  - name: attendease-db
    databaseName: attendease
    user: attendease_user
    plan: free
