services:
  - type: web
    name: attendease-backend
    runtime: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: attendease-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        value: decukgzzw
      - key: CLOUDINARY_API_KEY
        value: 158315573237381
      - key: CLOUDINARY_API_SECRET
        value: ioeAAKr4SSDlVqjkTwWpB194gSI
      - key: STORAGE_TYPE
        value: cloudinary
      - key: UPLOAD_DIR
        value: /tmp/student_images
      - key: FACE_DETECTION_METHOD
        value: haar
      - key: FACE_RECOGNITION_MODEL
        value: hog
      - key: FACE_RECOGNITION_TOLERANCE
        value: 0.6
      - key: LOG_LEVEL
        value: INFO
      - key: ALLOWED_ORIGINS
        value: "*"
    healthCheckPath: /health

databases:
  - name: attendease-db
    databaseName: attendease
    user: attendease_user
    plan: free
